### ISSUE TITLE
Dont save visualizer_upload config via settings screen

### ISSUE THREAD

**Issue by Mimoja** [vjapolitzer/de1app_plugin_keyboard_control#1]
In: https://github.com/vjapolitzer/de1app_plugin_keyboard_control/blob/48edd72f1b2f71985dc2e6e35a84ebb5c2574d83/plugin.tcl#L124

You are referencing the visualizer_upload plugin for saving

**Comment by vjapolitzer** [comment]
@Mimoja Ah, good catch. Corrected reference to keyboard_control.
