### ISSUE TITLE
Metric skin is now registered as "Metric" instead of "metric"

### ISSUE THREAD

**Issue by Mimoja** [vjapolitzer/de1app_plugin_keyboard_control#4]
Checking for the lowercase skinname will no longer work

**Comment by vjapolitzer** [comment]
@Mimoja thanks for notifying me of this. I've patched it with a string tolower command to make it case agnostic.

I think I'd like to get rid of the check for Metric entirely, and I have a couple ideas, but this should suffice for the time being.
